# Generated by Django 2.0.2 on 2018-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='descr',
            field=models.CharField(default='ddt', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
