# Generated by Django 2.0.2 on 2018-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bucketlist_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='descr',
            field=models.CharField(max_length=255),
        ),
    ]
