# Generated by Django 2.0.2 on 2018-02-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180210_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='descr',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
